-- ============================================================
-- Campus Management System
-- 05-database-implementation/seed.sql
--
-- Purpose:
--   Inserts development/bootstrap data after schema.sql has
--   been executed successfully.
--
-- IMPORTANT:
--   1. This file is for DEVELOPMENT/INITIAL SETUP.
--   2. Never store plaintext passwords in the database.
--   3. Replace the example password hashes before using this
--      in any real deployment.
--   4. The initial ADMIN is created here through a controlled
--      bootstrap process, not through public registration.
-- ============================================================

USE campus_management;


-- ============================================================
-- 1. DEVELOPMENT ADMIN
-- ============================================================
--
-- IMPORTANT:
-- The password_hash below is an example bcrypt hash.
-- Replace it with a hash generated by the Java application
-- before using this seed in a real environment.
--
-- Example application flow:
--
-- Password
--    ↓
-- BCrypt
--    ↓
-- password_hash
--    ↓
-- users.password_hash
--
-- NEVER insert a plaintext password.
--

INSERT INTO users (
    email,
    password_hash,
    role,
    status
)
VALUES (
    'admin@campus.local',
    '$2a$10$REPLACE_THIS_WITH_A_REAL_BCRYPT_HASH',
    'ADMIN',
    'ACTIVE'
);


-- ============================================================
-- 2. DEPARTMENTS
-- ============================================================

INSERT INTO departments (
    department_code,
    department_name,
    status
)
VALUES
    ('CSE', 'Computer Science and Engineering', 'ACTIVE'),
    ('ME', 'Mechanical Engineering', 'ACTIVE'),
    ('CE', 'Civil Engineering', 'ACTIVE'),
    ('ECE', 'Electronics and Communication Engineering', 'ACTIVE'),
    ('EEE', 'Electrical and Electronics Engineering', 'ACTIVE');


-- ============================================================
-- 3. ACADEMIC YEAR
-- ============================================================

INSERT INTO academic_years (
    year_name,
    start_date,
    end_date,
    status
)
VALUES (
    '2026-2027',
    '2026-06-01',
    '2027-05-31',
    'ACTIVE'
);


-- ============================================================
-- 4. SEMESTERS
-- ============================================================

INSERT INTO semesters (
    academic_year_id,
    semester_number,
    semester_name,
    status
)
SELECT
    id,
    1,
    'S1',
    'ACTIVE'
FROM academic_years
WHERE year_name = '2026-2027';

INSERT INTO semesters (
    academic_year_id,
    semester_number,
    semester_name,
    status
)
SELECT
    id,
    2,
    'S2',
    'ACTIVE'
FROM academic_years
WHERE year_name = '2026-2027';

INSERT INTO semesters (
    academic_year_id,
    semester_number,
    semester_name,
    status
)
SELECT
    id,
    3,
    'S3',
    'ACTIVE'
FROM academic_years
WHERE year_name = '2026-2027';


-- ============================================================
-- 5. PERIODS
-- ============================================================
--
-- Example college timetable.
-- Change these times according to the actual college timetable.
--

INSERT INTO periods (
    period_number,
    start_time,
    end_time,
    status
)
VALUES
    (1, '09:30:00', '10:30:00', 'ACTIVE'),
    (2, '10:40:00', '11:40:00', 'ACTIVE'),
    (3, '11:40:00', '12:40:00', 'ACTIVE'),
    (4, '13:20:00', '14:20:00', 'ACTIVE'),
    (5, '14:20:00', '15:20:00', 'ACTIVE'),
    (6, '15:30:00', '16:30:00', 'ACTIVE');

-- ============================================================
-- 6. ROOMS
-- ============================================================

INSERT INTO rooms (
    room_number,
    building,
    room_type,
    capacity,
    status
)
VALUES
    ('CSE-101', 'Main Block', 'CLASSROOM', 60, 'ACTIVE'),
    ('CSE-102', 'Main Block', 'CLASSROOM', 60, 'ACTIVE'),
    ('CSE-LAB-1', 'Main Block', 'LAB', 30, 'ACTIVE'),
    ('CSE-LAB-2', 'Main Block', 'LAB', 30, 'ACTIVE'),
    ('SEM-01', 'Main Block', 'SEMINAR_HALL', 120, 'ACTIVE');


-- ============================================================
-- 7. SAMPLE FACULTY USERS
-- ============================================================
--
-- These accounts are development accounts.
-- Replace hashes and emails before real deployment.
--

INSERT INTO users (
    email,
    password_hash,
    role,
    status
)
VALUES
    (
        'faculty1@campus.local',
        '$2a$10$REPLACE_THIS_WITH_A_REAL_BCRYPT_HASH',
        'FACULTY',
        'ACTIVE'
    ),
    (
        'faculty2@campus.local',
        '$2a$10$REPLACE_THIS_WITH_A_REAL_BCRYPT_HASH',
        'FACULTY',
        'ACTIVE'
    );


-- ============================================================
-- 8. SAMPLE FACULTY PROFILES
-- ============================================================

INSERT INTO faculties (
    user_id,
    employee_id,
    department_id,
    status
)
SELECT
    u.id,
    'FAC001',
    d.id,
    'ACTIVE'
FROM users u
JOIN departments d
    ON d.department_code = 'CSE'
WHERE u.email = 'faculty1@campus.local';

INSERT INTO faculties (
    user_id,
    employee_id,
    department_id,
    status
)
SELECT
    u.id,
    'FAC002',
    d.id,
    'ACTIVE'
FROM users u
JOIN departments d
    ON d.department_code = 'CSE'
WHERE u.email = 'faculty2@campus.local';


-- ============================================================
-- 9. SAMPLE CLASS
-- ============================================================

INSERT INTO classes (
    class_name,
    department_id,
    semester_id,
    academic_year_id,
    section,
    status
)
SELECT
    'S3 CSE',
    d.id,
    s.id,
    ay.id,
    'A',
    'ACTIVE'
FROM departments d
JOIN semesters s
    ON s.semester_name = 'S3'
JOIN academic_years ay
    ON ay.year_name = '2026-2027'
WHERE d.department_code = 'CSE';


-- ============================================================
-- 10. SAMPLE STUDENT USER
-- ============================================================

INSERT INTO users (
    email,
    password_hash,
    role,
    status
)
VALUES (
    'student1@campus.local',
    '$2a$10$REPLACE_THIS_WITH_A_REAL_BCRYPT_HASH',
    'STUDENT',
    'ACTIVE'
);


-- ============================================================
-- 11. SAMPLE STUDENT PROFILE
-- ============================================================

INSERT INTO students (
    user_id,
    register_number,
    class_id,
    admission_year,
    status
)
SELECT
    u.id,
    'CSE2026001',
    c.id,
    2026,
    'ACTIVE'
FROM users u
JOIN classes c
    ON c.class_name = 'S3 CSE'
   AND c.section = 'A'
WHERE u.email = 'student1@campus.local';


-- ============================================================
-- 12. SAMPLE SUBJECTS
-- ============================================================

INSERT INTO subjects (
    subject_code,
    subject_name,
    department_id,
    semester_id,
    credits,
    subject_type,
    status
)
SELECT
    'CSE301',
    'Object Oriented Programming',
    d.id,
    s.id,
    4.0,
    'THEORY',
    'ACTIVE'
FROM departments d
JOIN semesters s
    ON s.semester_name = 'S3'
WHERE d.department_code = 'CSE';

INSERT INTO subjects (
    subject_code,
    subject_name,
    department_id,
    semester_id,
    credits,
    subject_type,
    status
)
SELECT
    'CSE302',
    'Data Structures',
    d.id,
    s.id,
    4.0,
    'THEORY',
    'ACTIVE'
FROM departments d
JOIN semesters s
    ON s.semester_name = 'S3'
WHERE d.department_code = 'CSE';

INSERT INTO subjects (
    subject_code,
    subject_name,
    department_id,
    semester_id,
    credits,
    subject_type,
    status
)
SELECT
    'CSE303',
    'Database Management Systems',
    d.id,
    s.id,
    4.0,
    'THEORY',
    'ACTIVE'
FROM departments d
JOIN semesters s
    ON s.semester_name = 'S3'
WHERE d.department_code = 'CSE';

INSERT INTO subjects (
    subject_code,
    subject_name,
    department_id,
    semester_id,
    credits,
    subject_type,
    status
)
SELECT
    'CSE304',
    'Database Management Systems Lab',
    d.id,
    s.id,
    2.0,
    'LAB',
    'ACTIVE'
FROM departments d
JOIN semesters s
    ON s.semester_name = 'S3'
WHERE d.department_code = 'CSE';


-- ============================================================
-- 13. CLASS-SUBJECT MAPPINGS
-- ============================================================

INSERT INTO class_subjects (
    class_id,
    subject_id,
    academic_year_id,
    semester_id,
    status
)
SELECT
    c.id,
    s.id,
    ay.id,
    sem.id,
    'ACTIVE'
FROM classes c
JOIN subjects s
    ON s.subject_code IN ('CSE301', 'CSE302', 'CSE303', 'CSE304')
JOIN academic_years ay
    ON ay.year_name = '2026-2027'
JOIN semesters sem
    ON sem.semester_name = 'S3'
WHERE c.class_name = 'S3 CSE'
  AND c.section = 'A';


-- ============================================================
-- 14. FACULTY-SUBJECT MAPPINGS
-- ============================================================

INSERT INTO faculty_subjects (
    faculty_id,
    subject_id,
    academic_year_id,
    semester_id,
    status
)
SELECT
    f.id,
    s.id,
    ay.id,
    sem.id,
    'ACTIVE'
FROM faculties f
JOIN subjects s
    ON s.subject_code IN ('CSE301', 'CSE303')
JOIN academic_years ay
    ON ay.year_name = '2026-2027'
JOIN semesters sem
    ON sem.semester_name = 'S3'
WHERE f.employee_id = 'FAC001';

INSERT INTO faculty_subjects (
    faculty_id,
    subject_id,
    academic_year_id,
    semester_id,
    status
)
SELECT
    f.id,
    s.id,
    ay.id,
    sem.id,
    'ACTIVE'
FROM faculties f
JOIN subjects s
    ON s.subject_code IN ('CSE302', 'CSE304')
JOIN academic_years ay
    ON ay.year_name = '2026-2027'
JOIN semesters sem
    ON sem.semester_name = 'S3'
WHERE f.employee_id = 'FAC002';


-- ============================================================
-- 15. SAMPLE MASTER TIMETABLE
-- ============================================================
--
-- Faculty 1:
--   OOP
--   DBMS
--
-- Faculty 2:
--   Data Structures
--   DBMS Lab
--

INSERT INTO timetables (
    class_id,
    subject_id,
    faculty_id,
    period_id,
    room_id,
    academic_year_id,
    semester_id,
    day_of_week,
    status
)
SELECT
    c.id,
    s.id,
    f.id,
    p.id,
    r.id,
    ay.id,
    sem.id,
    'MONDAY',
    'ACTIVE'
FROM classes c
JOIN subjects s
    ON s.subject_code = 'CSE301'
JOIN faculties f
    ON f.employee_id = 'FAC001'
JOIN periods p
    ON p.period_number = 1
JOIN rooms r
    ON r.room_number = 'CSE-101'
JOIN academic_years ay
    ON ay.year_name = '2026-2027'
JOIN semesters sem
    ON sem.semester_name = 'S3'
WHERE c.class_name = 'S3 CSE'
  AND c.section = 'A';

INSERT INTO timetables (
    class_id,
    subject_id,
    faculty_id,
    period_id,
    room_id,
    academic_year_id,
    semester_id,
    day_of_week,
    status
)
SELECT
    c.id,
    s.id,
    f.id,
    p.id,
    r.id,
    ay.id,
    sem.id,
    'MONDAY',
    'ACTIVE'
FROM classes c
JOIN subjects s
    ON s.subject_code = 'CSE302'
JOIN faculties f
    ON f.employee_id = 'FAC002'
JOIN periods p
    ON p.period_number = 2
JOIN rooms r
    ON r.room_number = 'CSE-101'
JOIN academic_years ay
    ON ay.year_name = '2026-2027'
JOIN semesters sem
    ON sem.semester_name = 'S3'
WHERE c.class_name = 'S3 CSE'
  AND c.section = 'A';

INSERT INTO timetables (
    class_id,
    subject_id,
    faculty_id,
    period_id,
    room_id,
    academic_year_id,
    semester_id,
    day_of_week,
    status
)
SELECT
    c.id,
    s.id,
    f.id,
    p.id,
    r.id,
    ay.id,
    sem.id,
    'TUESDAY',
    'ACTIVE'
FROM classes c
JOIN subjects s
    ON s.subject_code = 'CSE303'
JOIN faculties f
    ON f.employee_id = 'FAC001'
JOIN periods p
    ON p.period_number = 1
JOIN rooms r
    ON r.room_number = 'CSE-101'
JOIN academic_years ay
    ON ay.year_name = '2026-2027'
JOIN semesters sem
    ON sem.semester_name = 'S3'
WHERE c.class_name = 'S3 CSE'
  AND c.section = 'A';

INSERT INTO timetables (
    class_id,
    subject_id,
    faculty_id,
    period_id,
    room_id,
    academic_year_id,
    semester_id,
    day_of_week,
    status
)
SELECT
    c.id,
    s.id,
    f.id,
    p.id,
    r.id,
    ay.id,
    sem.id,
    'WEDNESDAY',
    'ACTIVE'
FROM classes c
JOIN subjects s
    ON s.subject_code = 'CSE304'
JOIN faculties f
    ON f.employee_id = 'FAC002'
JOIN periods p
    ON p.period_number = 3
JOIN rooms r
    ON r.room_number = 'CSE-LAB-1'
JOIN academic_years ay
    ON ay.year_name = '2026-2027'
JOIN semesters sem
    ON sem.semester_name = 'S3'
WHERE c.class_name = 'S3 CSE'
  AND c.section = 'A';


-- ============================================================
-- 16. SAMPLE NOTIFICATION PREFERENCES
-- ============================================================

INSERT INTO notification_preferences (
    user_id,
    in_app_enabled,
    email_enabled,
    whatsapp_enabled
)
SELECT
    id,
    TRUE,
    TRUE,
    FALSE
FROM users
WHERE email IN (
    'admin@campus.local',
    'faculty1@campus.local',
    'faculty2@campus.local',
    'student1@campus.local'
);


-- ============================================================
-- 17. DEVELOPMENT VERIFICATION QUERIES
-- ============================================================
--
-- Run these manually after seed.sql to verify the data.
--
-- SELECT * FROM users;
-- SELECT * FROM departments;
-- SELECT * FROM academic_years;
-- SELECT * FROM semesters;
-- SELECT * FROM classes;
-- SELECT * FROM students;
-- SELECT * FROM faculties;
-- SELECT * FROM subjects;
-- SELECT * FROM class_subjects;
-- SELECT * FROM faculty_subjects;
-- SELECT * FROM periods;
-- SELECT * FROM rooms;
-- SELECT * FROM timetables;
-- SELECT * FROM notification_preferences;
--
-- ============================================================


-- ============================================================
-- END OF SEED
-- ============================================================
